NEXT-37409 - Add licensed IAP flag and badge
shopware/SwagExtensionStore pull request #36
Opened 2024-10-29 14:44 UTC by lernhart

2024-10-29 15:06 UTC, Bird87ZA requested changes

2024-10-29 15:06 UTC, Bird87ZA commented on src/Resources/app/administration/src/module/sw-extension/snippet/de-DE.json
> +                "account-link-label": "In-App Einkäufe verwalten"
This is not the same as the English version.

```suggestion
                "account-link-label": "Einkäufe verwalten"
```

2024-10-29 15:07 UTC, Bird87ZA commented
I've already reported the Jest failure to @philipreinken.

2024-10-29 17:38 UTC, philipreinken commented
> I've already reported the Jest failure to @philipreinken.

See my comment [here](https://github.com/shopware/SwagExtensionStore/pull/27#discussion_r1821278582), one input-ID changed recently, which caused the dependency installation to be skipped.

2024-10-30 12:59 UTC, Bird87ZA approved these changes

2024-10-30 13:03 UTC, cyl3x approved these changes

2024-10-30 13:12 UTC, merged